#
# Build configuration for Circle CI
#

general:
  artifacts:
  - /home/ubuntu/AndroidDemo/app/build/outputs/apk/

machine:
  environment:
    ANDROID_HOME: C:\\Users\\User\\AppData\\Local\\Android\\Sdk

dependencies:
  override:
  - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-19.1.0,android-19,extra-google-m2repository,extra-google-google_play_services,extra-android-support
  - ANDROID_HOME=C:\\Users\\User\\AppData\\Local\\Android\\Sdk ./gradlew dependencies

test:
  override:
  - (./gradlew assemble):
      timeout: 360